# Generated by Django 3.2 on 2021-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_rename_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.BinaryField(blank=True),
        ),
    ]
